kind: pipeline
name: default

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: validate
    image: hashicorp/terraform:0.11.13
    commands:
      - terraform init -input=false
      - terraform validate -check-variables=false
    when:
      event:
        - pull_request

  - name: acctest-plan
    image: hashicorp/terraform:0.11.13
    commands:
      - cd acceptance-test
      - terraform init -input=false
      - terraform plan -input=false
    when:
      event:
        - pull_request

  - name: release-dry-run
    image: gtramontina/semantic-release:15.13.3
    commands:
      - semantic-release --dry-run
    when:
      event:
        - pull_request

  - name: release
    image: gtramontina/semantic-release:15.13.3
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - semantic-release
    when:
      event:
        - push
      branch:
        - master
